### ISSUE TITLE
Enabling this plugin blocks out IPv6 access in LAN

### ISSUE THREAD

**Issue by encombhat** [project-openwrt/luci-app-unblockneteasemusic#32] opened 2020-08-30 04:24 UTC
I have a working IPv6 connection(with prefix) and my router can successfully assign IPv6 addresses to devices in LAN.

However, enabling this plugin causes IPv6 connectivity in LAN to be unusable. The address is still assigned, but any attempt to ping an IPv6 address failed with: "Destination Unreachable: no route". Disabling this plugin and rebooting the router fixed it.

Is that an issue with iptables configuration in this plugin?

**Comment by 1715173329** [comment] 2020-09-05 15:07
Actually we never touch ipv6 route, maybe you need provide us more information to work with the issue.

**Comment by 1715173329** [comment] 2020-10-03 09:29
As we cannot reproduce your issue, I will close this.
You can reopen it anytime if more information is provided.

**Closed by 1715173329** 2020-10-03 09:29 UTC
